---
image: docker:git

tags:
  - docker

services:
  - docker:dind

stages:
  - lint

before_script:
  - apk add python3 make

lint:
  stage: lint
  script:
  - pip3 install flake8
  - flake8 .

build:
  stage: build
  script:
    - pip3 install -r build-requirements.txt
    - make -f build/Makefile build
  artifacts:
    paths:
      - dist/

release:
  stage: release
  only:
    - tags
  except:
    - branches
  dependencies:
    - build
  script:
    - pip3 install -r build-requirements.txt
    - make -f build/Makefile ci-push
